var annotated_dup =
[
    [ "__DMA_HandleTypeDef", "struct_____d_m_a___handle_type_def.html", "struct_____d_m_a___handle_type_def" ],
    [ "__UART_HandleTypeDef", "struct_____u_a_r_t___handle_type_def.html", "struct_____u_a_r_t___handle_type_def" ],
    [ "DMA_InitTypeDef", "struct_d_m_a___init_type_def.html", "struct_d_m_a___init_type_def" ],
    [ "EnvDataPacket_t", "struct_env_data_packet__t.html", "struct_env_data_packet__t" ],
    [ "EXTI_ConfigTypeDef", "struct_e_x_t_i___config_type_def.html", "struct_e_x_t_i___config_type_def" ],
    [ "EXTI_HandleTypeDef", "struct_e_x_t_i___handle_type_def.html", "struct_e_x_t_i___handle_type_def" ],
    [ "FLASH_EraseInitTypeDef", "struct_f_l_a_s_h___erase_init_type_def.html", "struct_f_l_a_s_h___erase_init_type_def" ],
    [ "FLASH_OBProgramInitTypeDef", "struct_f_l_a_s_h___o_b_program_init_type_def.html", "struct_f_l_a_s_h___o_b_program_init_type_def" ],
    [ "FLASH_ProcessTypeDef", "struct_f_l_a_s_h___process_type_def.html", "struct_f_l_a_s_h___process_type_def" ],
    [ "GPIO_InitTypeDef", "struct_g_p_i_o___init_type_def.html", "struct_g_p_i_o___init_type_def" ],
    [ "gps_data_t", "structgps__data__t.html", "structgps__data__t" ],
    [ "GpsDataPacket_t", "struct_gps_data_packet__t.html", "struct_gps_data_packet__t" ],
    [ "I2C_HandleTypeDef", "struct_i2_c___handle_type_def.html", "struct_i2_c___handle_type_def" ],
    [ "I2C_InitTypeDef", "struct_i2_c___init_type_def.html", "struct_i2_c___init_type_def" ],
    [ "ImuDataPacket_t", "struct_imu_data_packet__t.html", "struct_imu_data_packet__t" ],
    [ "LL_UTILS_ClkInitTypeDef", "struct_l_l___u_t_i_l_s___clk_init_type_def.html", "struct_l_l___u_t_i_l_s___clk_init_type_def" ],
    [ "LL_UTILS_PLLInitTypeDef", "struct_l_l___u_t_i_l_s___p_l_l_init_type_def.html", "struct_l_l___u_t_i_l_s___p_l_l_init_type_def" ],
    [ "PWR_PVDTypeDef", "struct_p_w_r___p_v_d_type_def.html", "struct_p_w_r___p_v_d_type_def" ],
    [ "RCC_ClkInitTypeDef", "struct_r_c_c___clk_init_type_def.html", "struct_r_c_c___clk_init_type_def" ],
    [ "RCC_OscInitTypeDef", "struct_r_c_c___osc_init_type_def.html", "struct_r_c_c___osc_init_type_def" ],
    [ "RCC_PLLInitTypeDef", "struct_r_c_c___p_l_l_init_type_def.html", "struct_r_c_c___p_l_l_init_type_def" ],
    [ "Sensor10DoF_t", "struct_sensor10_do_f__t.html", "struct_sensor10_do_f__t" ],
    [ "TIM_Base_InitTypeDef", "struct_t_i_m___base___init_type_def.html", "struct_t_i_m___base___init_type_def" ],
    [ "TIM_BreakDeadTimeConfigTypeDef", "struct_t_i_m___break_dead_time_config_type_def.html", "struct_t_i_m___break_dead_time_config_type_def" ],
    [ "TIM_ClearInputConfigTypeDef", "struct_t_i_m___clear_input_config_type_def.html", "struct_t_i_m___clear_input_config_type_def" ],
    [ "TIM_ClockConfigTypeDef", "struct_t_i_m___clock_config_type_def.html", "struct_t_i_m___clock_config_type_def" ],
    [ "TIM_Encoder_InitTypeDef", "struct_t_i_m___encoder___init_type_def.html", "struct_t_i_m___encoder___init_type_def" ],
    [ "TIM_HallSensor_InitTypeDef", "struct_t_i_m___hall_sensor___init_type_def.html", "struct_t_i_m___hall_sensor___init_type_def" ],
    [ "TIM_HandleTypeDef", "struct_t_i_m___handle_type_def.html", "struct_t_i_m___handle_type_def" ],
    [ "TIM_IC_InitTypeDef", "struct_t_i_m___i_c___init_type_def.html", "struct_t_i_m___i_c___init_type_def" ],
    [ "TIM_MasterConfigTypeDef", "struct_t_i_m___master_config_type_def.html", "struct_t_i_m___master_config_type_def" ],
    [ "TIM_OC_InitTypeDef", "struct_t_i_m___o_c___init_type_def.html", "struct_t_i_m___o_c___init_type_def" ],
    [ "TIM_OnePulse_InitTypeDef", "struct_t_i_m___one_pulse___init_type_def.html", "struct_t_i_m___one_pulse___init_type_def" ],
    [ "TIM_SlaveConfigTypeDef", "struct_t_i_m___slave_config_type_def.html", "struct_t_i_m___slave_config_type_def" ],
    [ "UART_InitTypeDef", "struct_u_a_r_t___init_type_def.html", "struct_u_a_r_t___init_type_def" ]
];